### ISSUE TITLE
"pkg_resources.DistributionNotFound: argparse" w/Python 2.7

### ISSUE THREAD

**Issue by equaeghe** [domenkozar/g-pypi#13]
I've just installed g-pypi on my mostly stable Gentoo installation. My Python version is 2.7.3-r3, which as far as I know includes argparse (i.e., an external module is not needed). Nevertheless, when trying to create an ebuild (`gpypi create IMAPClient`) I get the following:

``` python
Traceback (most recent call last):
  File "/usr/bin/gpypi-2.7", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2808, in <module>
    working_set.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 691, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 589, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: argparse
```

**Comment by freeyoung** [comment]
Also got this error message on Gentoo with Python 2.7.3.
