### ISSUE TITLE
No such file or directory in workflow.py

### ISSUE THREAD

**Issue by weedy** [domenkozar/g-pypi#5]
After hardcoding **version** next up:

<pre>
# /usr/bin/gpypi create --overlay sunrise g-pypi2
 * Generating ebuild: g-pypi2 0.1
 * No '/var/lib/layman/pythonhead/profiles/repo_name', skipping
 * Added metadata.xml file
Traceback (most recent call last):
  File "/usr/bin/gpypi", line 9, in <module>
    load_entry_point('g-pypi==0.1dev', 'console_scripts', 'gpypi')()
  File "/usr/lib64/python2.7/site-packages/g_pypi-0.1dev-py2.7.egg/gpypi/cli.py", line 410, in main
    CLI(config_mgr)
  File "/usr/lib64/python2.7/site-packages/g_pypi-0.1dev-py2.7.egg/gpypi/cli.py", line 208, in __init__
    getattr(self, config.command)()
  File "/usr/lib64/python2.7/site-packages/g_pypi-0.1dev-py2.7.egg/gpypi/cli.py", line 215, in create
    gpypi.create_ebuilds()
  File "/usr/lib64/python2.7/site-packages/g_pypi-0.1dev-py2.7.egg/gpypi/cli.py", line 64, in create_ebuilds
    requires = self.do_ebuild()
  File "/usr/lib64/python2.7/site-packages/g_pypi-0.1dev-py2.7.egg/gpypi/cli.py", line 175, in do_ebuild
    ebuild.create()
  File "/usr/lib64/python2.7/site-packages/g_pypi-0.1dev-py2.7.egg/gpypi/ebuild.py", line 470, in create
    Echangelog(self.options, os.path.dirname(self.ebuild_path))()
  File "/usr/lib64/python2.7/site-packages/g_pypi-0.1dev-py2.7.egg/gpypi/workflow.py", line 124, in __call__
    if self.command('echangelog %s' % msg):
  File "/usr/lib64/python2.7/site-packages/g_pypi-0.1dev-py2.7.egg/gpypi/workflow.py", line 52, in command
    self.p = Popen(cmd.split(), cwd=self.path, stderr=STDOUT, stdout=PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
</pre>

**Comment by domenkozar** [comment]
You need gentoolkit and gentoolkit-dev installed. I agree there should be a warning.
